version: "3"
services:
  app:
    build: .
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "True"
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
  db:
    image: mysql:latest
    volumes:
      # - "./databases:/var/lib/mysql/chat.log"
      - "db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    expose:
      - 3306
      - 33060
    depends_on:
      - app
volumes:
  db-volume:
